/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './public/index.php',
        './view/**/*.php',
        './public/assets/js/**/*.js',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                /* Admin dashboard light area */
                'admin-bg': '#EEF2EF',
                'admin-card': '#FFFFFF',
                'admin-topbar': 'rgba(238, 242, 239, 0.92)',
                putihHangat: '#FBF8F1',
                kuning: '#E7A825',
                kuningHover: '#C98F1B',
                hijau: '#3C6E47',
                coklat: '#33291E',
                abu: '#6B655C',

                'lime-glow': 'rgba(158, 230, 56, 0.25)',
                secondary: '#bdcac0',
                'surface-bright': '#2a3d33',
                surface: '#05170e',
                'on-secondary': '#28332c',
                'on-primary-fixed-variant': '#304f00',
                'inverse-on-surface': '#22342b',
                'surface-variant': '#26392f',
                background: '#05170e',
                'status-success': '#1E3A21',
                outline: '#8c947d',
                'surface-dim': '#05170e',
                'primary-fixed': '#aef849',
                'muted-forest': '#1A2E23',
                'on-error': '#690005',
                'surface-tint': '#93da2c',
                'on-surface-variant': '#c1cab0',
                'status-error': '#3D1E1E',
                'on-tertiary': '#2a322e',
                'on-tertiary-container': '#535c56',
                'on-primary-container': '#3e6400',
                'on-primary': '#203600',
                'inverse-primary': '#426900',
                'primary-container': '#9ee638',
                'surface-container': '#11231a',
                tertiary: '#e7f0e9',
                'primary-fixed-dim': '#93da2c',
                'glass-border': 'rgba(255, 255, 255, 0.08)',
                'tertiary-fixed': '#dce5dd',
                'glass-fill': 'rgba(22, 37, 30, 0.65)',
                'on-error-container': '#ffdad6',
                'tertiary-fixed-dim': '#c0c9c2',
                primary: '#c8ff80',
                'on-secondary-container': '#afbcb2',
                'surface-container-lowest': '#011109',
                'status-warning': '#3D2E14',
                'on-secondary-fixed-variant': '#3e4942',
                'secondary-fixed': '#d9e6dc',
                'error-container': '#93000a',
                'outline-variant': '#424936',
                'on-background': '#d2e8d9',
                'inverse-surface': '#d2e8d9',
                'secondary-container': '#404c44',
                'secondary-fixed-dim': '#bdcac0',
                'surface-container-high': '#1b2e24',
                'on-secondary-fixed': '#131e18',
                'on-surface': '#d2e8d9',
                'on-primary-fixed': '#112000',
                'on-tertiary-fixed': '#151d19',
                'surface-container-low': '#0d1f16',
                'tertiary-container': '#cbd4cd',
                'on-tertiary-fixed-variant': '#404944',
                'surface-container-highest': '#26392f',
                error: '#ffb4ab',
            },
            spacing: {
                'stack-sm': '8px',
                'stack-md': '14px',
                'stack-lg': '24px',
                'section-gap': '64px',
                'margin-desktop': '28px',
                'margin-mobile': '16px',
                gutter: '20px',
                'container-max': '1280px',
            },
            fontFamily: {
                display: ['"Space Grotesk"', 'sans-serif'],
                body: ['"Plus Jakarta Sans"', 'sans-serif'],
                mono: ['"JetBrains Mono"', 'monospace'],
                caption: ['"Plus Jakarta Sans"', 'sans-serif'],
                'headline-xl-mobile': ['"Space Grotesk"', 'sans-serif'],
                'headline-xl': ['"Space Grotesk"', 'sans-serif'],
                'label-mono': ['"JetBrains Mono"', 'monospace'],
                'headline-lg': ['"Space Grotesk"', 'sans-serif'],
                'headline-md': ['"Space Grotesk"', 'sans-serif'],
                'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
                'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
            },
            fontSize: {
                caption: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
                'headline-xl-mobile': ['26px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
                'headline-xl': ['42px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
                'label-mono': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
                'headline-lg': ['28px', { lineHeight: '1.25', fontWeight: '700' }],
                'headline-md': ['19px', { lineHeight: '1.35', fontWeight: '600' }],
                'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'body-md': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
            },
            borderRadius: {
                kartu: '14px',
            },
            boxShadow: {
                kartu: '0 4px 16px rgba(51, 41, 30, 0.08)',
                hover: '0 8px 24px rgba(51, 41, 30, 0.14)',
            },
        },
    },
    plugins: [],
    safelist: [
        /* gallery lightbox & confirm modal — class dipakai di JS string */
        'fixed', 'inset-0', 'z-[200]', 'z-[201]',
        'flex', 'items-center', 'justify-center', 'justify-end',
        'bg-black/85', 'bg-black/70', 'backdrop-blur-sm',
        'relative', 'max-w-[92vw]', 'max-h-[92vh]', 'flex-col',
        '-top-10', 'right-0', 'w-9', 'h-9', 'rounded-full',
        'bg-white/15', 'bg-white/30', 'border', 'border-white/20',
        'text-white', 'transition-all', 'text-[20px]', 'absolute',
        'max-w-full', 'max-h-[85vh]', 'object-contain',
        'rounded-xl', 'shadow-2xl', 'block',
        /* confirm modal */
        'bg-surface-container-highest', 'border-glass-border', 'rounded-2xl',
        'p-6', 'max-w-sm', 'w-full', 'mx-4', 'gap-5',
        'gap-3', 'w-10', 'h-10', 'bg-red-500/10',
        'shrink-0', 'text-red-400',
        'text-base', 'font-semibold', 'text-on-surface', 'leading-tight',
        'text-sm', 'text-on-surface-variant', 'mt-0.5',
        'px-4', 'py-2', 'border-glass-border', 'text-on-surface-variant',
        'hover:text-on-surface',
        'bg-red-500', 'hover:bg-red-600', 'font-medium',
        'gap-[8px]', 'overflow-hidden',
        /* baris tabel yang dirender dari function/ajax.php */
        'border-black/6', 'text-red-600', 'hover:bg-red-50',
        /* kartu wisata dirender dari function/ajax.php (folder function tidak di-scan) */
        'aspect-[4/3]', 'aspect-[8/3]',
        /* modal + lightbox dari JS string (admin.js, media.js) */
        'z-[210]', 'z-[211]', 'z-[220]', 'z-[100]',
        'bg-black/75', 'bg-black/90', 'bg-black/30',
        '-top-14', 'max-w-5xl', 'max-h-[80vh]',
        'bg-white/10', 'hover:bg-white/25',
        'bg-white/5', 'hover:bg-white/15', 'hover:bg-white/10',
        'bg-red-600/90', 'border-red-500/40',
        'bg-green-400', 'gap-0.5', 'h-0.5', 'pr-12', 'break-words',
        'backdrop-blur-[1px]',
    ],
};
